version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    restart: unless-stopped
    depends_on:
      - backend